import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn } from 'node:child_process';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const sourceDir = path.join(__dirname, 'assets', 'src', 'css', 'main');
const componentsDir = path.join(sourceDir, 'components');
const outputFile = path.join(__dirname, 'assets', 'src', 'main.css');

const orderedMainFiles = ['base.css', 'utilities.css'];

const orderedComponentFiles = [
  'jagawarta-core-ui.css',
  'jagawarta-layout.css',
  'jagawarta-navigation.css',
  'jagawarta-archive-cards.css',
  'jagawarta-reading-toolbar.css',
  'jagawarta-share-modal.css',
  'jagawarta-home-sections.css',
];

const header = [
  '/* Generated by build-css.mjs — edit assets/src/css/main/*.css and assets/src/css/main/components/*.css */',
  '@tailwind base;',
  '@tailwind components;',
  '@tailwind utilities;',
  '',
].join('\n');

function readFileOrThrow(filePath) {
  if (!fs.existsSync(filePath)) {
    throw new Error(`Missing CSS source file: ${path.relative(__dirname, filePath)}`);
  }
  return fs.readFileSync(filePath, 'utf8').trimEnd();
}

function buildMainCss() {
  const mainParts = orderedMainFiles.map((name) => readFileOrThrow(path.join(sourceDir, name)));
  const componentParts = orderedComponentFiles.map((name) => readFileOrThrow(path.join(componentsDir, name)));
  const componentsLayer = `@layer components {\n\n${componentParts.join('\n\n')}\n}`;
  const content = `${header}${mainParts.join('\n\n')}\n\n${componentsLayer}\n`;

  const prev = fs.existsSync(outputFile) ? fs.readFileSync(outputFile, 'utf8') : '';
  if (prev !== content) {
    fs.writeFileSync(outputFile, content, 'utf8');
    console.log(`[build-css] Updated ${path.relative(__dirname, outputFile)}`);
  }
  else {
    console.log('[build-css] No changes');
  }
}

function runTailwindWatch() {
  const binName = process.platform === 'win32' ? 'tailwindcss.cmd' : 'tailwindcss';
  const tailwindBin = path.join(__dirname, 'node_modules', '.bin', binName);
  const args = ['-i', './assets/src/main.css', '-o', './assets/dist/main.css', '--watch'];

  const child = spawn(tailwindBin, args, {
    cwd: __dirname,
    stdio: 'inherit',
  });

  const shutdown = () => {
    child.kill('SIGTERM');
    process.exit(0);
  };

  process.on('SIGINT', shutdown);
  process.on('SIGTERM', shutdown);

  child.on('exit', (code) => {
    process.exit(code ?? 0);
  });
}

function watchSources() {
  let timer = null;

  fs.watch(sourceDir, { recursive: true }, (_eventType, filename) => {
    if (!filename || !filename.endsWith('.css')) {
      return;
    }

    clearTimeout(timer);
    timer = setTimeout(() => {
      try {
        buildMainCss();
      }
      catch (error) {
        console.error('[build-css] Build failed:', error.message);
      }
    }, 60);
  });

  console.log(`[build-css] Watching ${path.relative(__dirname, sourceDir)}`);
}

const shouldWatch = process.argv.includes('--watch');

try {
  buildMainCss();

  if (shouldWatch) {
    watchSources();
    runTailwindWatch();
  }
}
catch (error) {
  console.error('[build-css] Build failed:', error.message);
  process.exit(1);
}
