/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './**/*.php',
    './assets/src/**/*.js',
    './assets/src/**/*.css',
  ],
  theme: {
    extend: {
      colors: {
        background: 'var(--md-color-background)',
        surface: 'var(--md-color-surface)',
        'surface-low': 'var(--md-color-surface-container-low)',
        'surface-mid': 'var(--md-color-surface-container)',
        'surface-high': 'var(--md-color-surface-container-high)',
        'on-surface': 'var(--md-color-on-surface)',
        'on-surface-variant': 'var(--md-color-on-surface-variant)',
        primary: 'var(--md-color-primary)',
        'on-primary': 'var(--md-color-on-primary)',
        'primary-container': 'var(--md-color-primary-container)',
        'on-primary-container': 'var(--md-color-on-primary-container)',
        'secondary-container': 'var(--md-color-secondary-container)',
        'on-secondary-container': 'var(--md-color-on-secondary-container)',
        'error-container': 'var(--md-color-error-container)',
        'on-error-container': 'var(--md-color-on-error-container)',
        outline: 'var(--md-color-outline)',
        'outline-variant': 'var(--md-color-outline-variant)',
        scrim: 'var(--md-color-scrim)',
      },
      fontFamily: {
        sans: ['var(--md-sys-font-family-sans)'],
        serif: ['var(--md-sys-font-family-serif)'],
      },
      borderRadius: {
        sm: 'var(--md-shape-corner-small)',
        md: 'var(--md-shape-corner-medium)',
        full: 'var(--md-shape-corner-full)',
      },
      fontSize: {
        'display-large': ['var(--md-sys-typescale-display-large-size)', { lineHeight: 'var(--md-sys-typescale-display-large-line-height)', fontWeight: 'var(--md-sys-typescale-display-large-weight)' }],
        'display-medium': ['var(--md-sys-typescale-display-medium-size)', { lineHeight: 'var(--md-sys-typescale-display-medium-line-height)', fontWeight: 'var(--md-sys-typescale-display-medium-weight)' }],
        'display-small': ['var(--md-sys-typescale-display-small-size)', { lineHeight: 'var(--md-sys-typescale-display-small-line-height)', fontWeight: 'var(--md-sys-typescale-display-small-weight)' }],
        'headline-large': ['var(--md-sys-typescale-headline-large-size)', { lineHeight: 'var(--md-sys-typescale-headline-large-line-height)', fontWeight: 'var(--md-sys-typescale-headline-large-weight)' }],
        'headline-medium': ['var(--md-sys-typescale-headline-medium-size)', { lineHeight: 'var(--md-sys-typescale-headline-medium-line-height)', fontWeight: 'var(--md-sys-typescale-headline-medium-weight)' }],
        'headline-small': ['var(--md-sys-typescale-headline-small-size)', { lineHeight: 'var(--md-sys-typescale-headline-small-line-height)', fontWeight: 'var(--md-sys-typescale-headline-small-weight)' }],
        'title-large': ['var(--md-sys-typescale-title-large-size)', { lineHeight: 'var(--md-sys-typescale-title-large-line-height)', fontWeight: 'var(--md-sys-typescale-title-large-weight)' }],
        'title-medium': ['var(--md-sys-typescale-title-medium-size)', { lineHeight: 'var(--md-sys-typescale-title-medium-line-height)', fontWeight: 'var(--md-sys-typescale-title-medium-weight)' }],
        'title-small': ['var(--md-sys-typescale-title-small-size)', { lineHeight: 'var(--md-sys-typescale-title-small-line-height)', fontWeight: 'var(--md-sys-typescale-title-small-weight)' }],
        'body-large': ['var(--md-sys-typescale-body-large-size)', { lineHeight: 'var(--md-sys-typescale-body-large-line-height)', fontWeight: 'var(--md-sys-typescale-body-large-weight)' }],
        'body-medium': ['var(--md-sys-typescale-body-medium-size)', { lineHeight: 'var(--md-sys-typescale-body-medium-line-height)', fontWeight: 'var(--md-sys-typescale-body-medium-weight)' }],
        'body-small': ['var(--md-sys-typescale-body-small-size)', { lineHeight: 'var(--md-sys-typescale-body-small-line-height)', fontWeight: 'var(--md-sys-typescale-body-small-weight)' }],
        'label-large': ['var(--md-sys-typescale-label-large-size)', { lineHeight: 'var(--md-sys-typescale-label-large-line-height)', fontWeight: 'var(--md-sys-typescale-label-large-weight)' }],
        'label-medium': ['var(--md-sys-typescale-label-medium-size)', { lineHeight: 'var(--md-sys-typescale-label-medium-line-height)', fontWeight: 'var(--md-sys-typescale-label-medium-weight)' }],
        'label-small': ['var(--md-sys-typescale-label-small-size)', { lineHeight: 'var(--md-sys-typescale-label-small-line-height)', fontWeight: 'var(--md-sys-typescale-label-small-weight)' }],
      },
      spacing: {
        0: 'var(--md-sys-spacing-0)',
        '0.5': 'var(--md-sys-spacing-0-5)',
        1: 'var(--md-sys-spacing-1)',
        '1.5': 'var(--md-sys-spacing-1-5)',
        2: 'var(--md-sys-spacing-2)',
        '2.5': 'var(--md-sys-spacing-2-5)',
        3: 'var(--md-sys-spacing-3)',
        '3.5': 'var(--md-sys-spacing-3-5)',
        4: 'var(--md-sys-spacing-4)',
        5: 'var(--md-sys-spacing-5)',
        6: 'var(--md-sys-spacing-6)',
        7: 'var(--md-sys-spacing-7)',
        8: 'var(--md-sys-spacing-8)',
        9: 'var(--md-sys-spacing-9)',
        10: 'var(--md-sys-spacing-10)',
        11: 'var(--md-sys-spacing-11)',
        12: 'var(--md-sys-spacing-12)',
        14: 'var(--md-sys-spacing-14)',
        16: 'var(--md-sys-spacing-16)',
        20: 'var(--md-sys-spacing-20)',
        24: 'var(--md-sys-spacing-24)',
        28: 'var(--md-sys-spacing-28)',
        32: 'var(--md-sys-spacing-32)',
        36: 'var(--md-sys-spacing-36)',
        40: 'var(--md-sys-spacing-40)',
        44: 'var(--md-sys-spacing-44)',
        48: 'var(--md-sys-spacing-48)',
        52: 'var(--md-sys-spacing-52)',
        56: 'var(--md-sys-spacing-56)',
        60: 'var(--md-sys-spacing-60)',
        64: 'var(--md-sys-spacing-64)',
        72: 'var(--md-sys-spacing-72)',
        80: 'var(--md-sys-spacing-80)',
        96: 'var(--md-sys-spacing-96)',
      },
      boxShadow: {
        'elevation-0': 'var(--md-sys-elevation-0)',
        'elevation-1': 'var(--md-sys-elevation-1)',
        'elevation-2': 'var(--md-sys-elevation-2)',
        'elevation-3': 'var(--md-sys-elevation-3)',
        'elevation-4': 'var(--md-sys-elevation-4)',
        'elevation-5': 'var(--md-sys-elevation-5)',
      },
      transitionDuration: {
        short: 'var(--md-sys-motion-duration-short)',
        medium: 'var(--md-sys-motion-duration-medium)',
      },
      transitionTimingFunction: {
        standard: 'var(--md-sys-motion-easing-standard)',
        emphasized: 'var(--md-sys-motion-easing-emphasized)',
      },
    },
  },
  plugins: [],
};
